import storyJson from "@/content/story/story.json";
import type { LocalizedText } from "@/lib/book";

/**
 * 『돌아서 간 길』 / The Long Way Round — Sungmin Kim's six-part
 * autobiographical essay, the web edition.
 *
 * `src/content/story/story.json` is generated by `scripts/build-story.mjs`
 * from the approved manuscripts in `docs/story/`. The Korean body text is
 * verbatim; English titles and summaries are authored in English
 * (`story-meta.json`) and are the canonical wording for the reader chrome.
 * The English edition of each episode (`src/content/story/en/<slug>.html`)
 * is written from the Korean text, facts one to one, and merged in by the
 * same script as `htmlEn`.
 */

export type StoryEpisode = {
  slug: string;
  order: number;
  labelKo: string;
  labelEn: string;
  title: string;
  titleEn: string;
  summaryEn: string;
  /** Opening sentences of the episode, verbatim — used as the Korean description. */
  excerpt: string;
  chars: number;
  readingMinutes: number;
  html: string;
  htmlEn?: string;
  wordsEn?: number;
  readingMinutesEn?: number;
};

export type StoryData = {
  generatedAt: string;
  source: { branch: string; commit: string; files: string[] };
  title: LocalizedText;
  author: LocalizedText;
  totalChars: number;
  totalMinutes: number;
  totalWordsEn: number;
  totalMinutesEn: number;
  episodes: StoryEpisode[];
};

export const STORY: StoryData = storyJson;

export const STORY_PATH = "/story";
export const STORY_URL = "https://mathkim-zeta.vercel.app/story";

export function hasEnglish(
  episode: StoryEpisode,
): episode is StoryEpisode & Required<Pick<StoryEpisode, "htmlEn" | "wordsEn" | "readingMinutesEn">> {
  return (
    Boolean(episode.htmlEn) &&
    episode.wordsEn !== undefined &&
    episode.readingMinutesEn !== undefined
  );
}

export const ENGLISH_EPISODE_COUNT = STORY.episodes.filter(hasEnglish).length;

/** Series line for the cover and metadata. Korean: the closing paragraph of episode 6, verbatim. */
export const STORY_SUBTITLE: LocalizedText = {
  ko: "대전에서 서울로, 서울에서 케임브리지로, 케임브리지에서 고1 교실로, 교실에서 다시 시험장으로, 그리고 12월의 무대로.",
  en: "From Daejeon to Seoul, from Seoul to Cambridge, from Cambridge to a grade-10 classroom, from the classroom back to the exam hall, and on to the stage in December.",
};

export const STORY_DESCRIPTION: LocalizedText = {
  ko: `${STORY.author.ko}의 자전 에세이 ${STORY.episodes.length}편. ${STORY_SUBTITLE.ko}`,
  en: `Six autobiographical essays by ${STORY.author.en}: from a child in Daejeon who read car number plates, through Trinity College, Cambridge, to sitting Korea's university entrance exams again as a working instructor, and on to the December 2026 launch on Daesung MyMac.`,
};

export function episodePath(slug: string): string {
  return `${STORY_PATH}/${slug}`;
}

export function getEpisode(slug: string): StoryEpisode | undefined {
  return STORY.episodes.find((episode) => episode.slug === slug);
}

export function getAdjacentEpisodes(slug: string): {
  prev: StoryEpisode | null;
  next: StoryEpisode | null;
} {
  const index = STORY.episodes.findIndex((episode) => episode.slug === slug);
  if (index < 0) return { prev: null, next: null };
  return {
    prev: index > 0 ? STORY.episodes[index - 1] : null,
    next: index < STORY.episodes.length - 1 ? STORY.episodes[index + 1] : null,
  };
}
